

const SONGS = [
  { id: 1, title: "We Are Bulletproof Pt.2", artist: "BTS", cover: "2cool4Skool.jpg" },
  { id: 2, title: "No More Dreams", artist: "BTS", cover: "2cool4Skool.jpg" },
  { id: 3, title: "Like", artist: "BTS", cover: "2cool4Skool.jpg" },
  { id: 4, title: "Attack on Bangtan", artist: "BTS", cover: "ORUL82.jpg" },
  { id: 5, title: "Boy in Luv", artist: "BTS", cover: "SkoolLuvAffair.jpg" },
  { id: 6, title: "Just One Day", artist: "BTS", cover: "SkoolLuvAffair.jpg" },
  { id: 7, title: "Spine Breaker", artist: "BTS", cover: "SkoolLuvAffair.jpg" },
  { id: 8, title: "Jump", artist: "BTS", cover: "SkoolLuvAffair.jpg" },
  { id: 9, title: "Danger", artist: "BTS", cover: "Dark&Wild.jpg" },
  { id: 10, title: "War of Hormone", artist: "BTS", cover: "Dark&Wild.jpg" },
  { id: 11, title: "BTS Cypher Pt.3: Killer", artist: "BTS", cover: "Dark&Wild.jpg" },
  { id: 12, title: "Look Here", artist: "BTS", cover: "Dark&Wild.jpg" },
  { id: 13, title: "I Need U", artist: "BTS", cover: "TheMostBeautifulMomentinLifePt1.jpg" },
  { id: 14, title: "Dope", artist: "BTS", cover: "TheMostBeautifulMomentinLifePt1.jpg" },
  { id: 15, title: "Run", artist: "BTS", cover: "TheMostBeautifulMomentinLifePt2.jpg" },
  { id: 16, title: "Butterfly", artist: "BTS", cover: "TheMostBeautifulMomentinLifePt2.jpg" },
  { id: 17, title: "Ma City", artist: "BTS", cover: "TheMostBeautifulMomentinLifePt2.jpg" },
  { id: 18, title: "Silver Spoon", artist: "BTS", cover: "TheMostBeautifulMomentinLifePt2.jpg" },
  { id: 19, title: "House of Cards(Full Length Edition)", artist: "BTS", cover: "TheMostBeautifulMomentinLifeYoungForever.jpg" },
  { id: 20, title: "Butterfly (Prologue Mix)", artist: "BTS", cover: "TheMostBeautifulMomentinLifeYoungForever.jpg" },
  { id: 21, title: "Burning Up (Fire)", artist: "BTS", cover: "TheMostBeautifulMomentinLifeYoungForever.jpg" },
  { id: 22, title: "Save Me", artist: "BTS", cover: "TheMostBeautifulMomentinLifeYoungForever.jpg" },
  { id: 23, title: "Epilogue: Young Forever", artist: "BTS", cover: "TheMostBeautifulMomentinLifeYoungForever.jpg" },
  { id: 24, title: "2!3!", artist: "BTS", cover: "Wings.jpg" },
  { id: 25, title: "For You", artist: "BTS", cover: "Youth.jpg" },
  { id: 26, title: "Blood Sweat & Tears", artist: "BTS", cover: "Wings.jpg" },
  { id: 27, title: "BTS Cypher 4", artist: "BTS", cover: "Wings.jpg" },
  { id: 28, title: "Spring Day", artist: "BTS", cover: "YouNeverWalkAlone.jpg" },
  { id: 29, title: "Best of Me", artist: "BTS", cover: "LoveYourselfHer.jpg" },
  { id: 30, title: "Dimple", artist: "BTS", cover: "LoveYourselfHer.jpg" },
  { id: 31, title: "So What", artist: "BTS", cover: "LoveYourselfTear.jpg" },
  { id: 32, title: "Pied Piper", artist: "BTS", cover: "LoveYourselfHer.jpg" },
  { id: 33, title: "MIC DROP", artist: "BTS", cover: "LoveYourselfHer.jpg" },
  { id: 34, title: "Go Go", artist: "BTS", cover: "LoveYourselfHer.jpg" },
  { id: 35, title: "Let Go", artist: "BTS", cover: "FaceYourself.jpg" },
  { id: 36, title: "Crystal Snow", artist: "BTS", cover: "FaceYourself.jpg" },
  { id: 37, title: "Magic Shop", artist: "BTS", cover: "LoveYourselfTear.jpg" },
  { id: 38, title: "Anpanman", artist: "BTS", cover: "LoveYourselfTear.jpg" },
  { id: 39, title: "Fake Love", artist: "BTS", cover: "LoveYourselfTear.jpg" },
  { id: 40, title: "The Truth Untold", artist: "BTS", cover: "LoveYourselfTear.jpg" },
  { id: 41, title: "Answer: Love Myself", artist: "BTS", cover: "LoveYourselfAnswer.jpg" },
  { id: 42, title: "Love Maze", artist: "BTS", cover: "LoveYourselfTear.jpg" },
  { id: 43, title: "Paradise", artist: "BTS", cover: "LoveYourselfTear.jpg" },
  { id: 44, title: "Airplane pt.2", artist: "BTS", cover: "LoveYourselfTear.jpg" },
  { id: 45, title: "I'm Fine", artist: "BTS", cover: "LoveYourselfAnswer.jpg" },
  { id: 46, title: "DNA", artist: "BTS", cover: "LoveYourselfAnswer.jpg" },
  { id: 47, title: "Mikrokosmos", artist: "BTS", cover: "MapofTheSoulPersona.jpg" },
  { id: 48, title: "Make It Right", artist: "BTS", cover: "MakeitRight.jpg" },
  { id: 49, title: "HOME", artist: "BTS", cover: "MapofTheSoulPersona.jpg" },
  { id: 50, title: "Dionysus", artist: "BTS", cover: "MapofTheSoulPersona.jpg" },
  { id: 51, title: "Boy With Luv(feat. Halsey)", artist: "BTS", cover: "MapofTheSoulPersona.jpg" },
  { id: 52, title: "Louder than Bombs", artist: "BTS", cover: "MapofTheSoul7.jpg" },
  { id: 53, title: "00:00 (Zero O'Clock)", artist: "BTS", cover: "MapofTheSoul7.jpg" },
  { id: 54, title: "UGH!", artist: "BTS", cover: "MapofTheSoul7.jpg" },
  { id: 55, title: "We are Bulletproof: the Eternal", artist: "BTS", cover: "MapofTheSoul7.jpg" },
  { id: 56, title: "Stay Gold", artist: "BTS", cover: "MapofTheSoul7TheJourney.jpg" },
  { id: 57, title: "Lights", artist: "BTS", cover: "Lights.jpg" },
  { id: 58, title: "Your eyes tell", artist: "BTS", cover: "MapofTheSoul7TheJourney.jpg" },
  { id: 59, title: "Life Goes On", artist: "BTS", cover: "BE.jpg" },
  { id: 60, title: "Blue & Grey", artist: "BTS", cover: "BE.jpg" },
  { id: 61, title: "Telepathy", artist: "BTS", cover: "BE.jpg" },
  { id: 62, title: "Dynamite", artist: "BTS", cover: "Dynamite.jpg" },
  { id: 63, title: "Yet To Come", artist: "BTS", cover: "Proof.jpg" },
  { id: 64, title: "For Youth", artist: "BTS", cover: "Proof.jpg" },
  { id: 65, title: "Run BTS", artist: "BTS", cover: "Proof.jpg" },
  { id: 66, title: "Take Two", artist: "BTS", cover: "TakeTwo.jpg" },
  { id: 67, title: "My Universe", artist: "BTS", cover: "MyUniverse.jpg" },
  { id: 68, title: "Permission to Dance", artist: "BTS", cover: "PTD.jpg" },
  { id: 69, title: "Butter", artist: "BTS", cover: "Butter.jpg" },
  { id: 70, title: "Film out", artist: "BTS", cover: "FilmOut.jpg" },
  { id: 71, title: "Black Swan", artist: "BTS", cover: "BlackSwan.jpg" },
  { id: 72, title: "Boyz with Fun", artist: "BTS", cover: "TheMostBeautifulMomentinLifePt1.jpg" },


  { id: 73, title: "Do You", artist: "RM", cover: "DoYou.jpg" },
  { id: 74, title: "No.2(with parkjiyoon)", artist: "RM", cover: "Indigo.jpg" },
  { id: 75, title: "seoul(prod. HONNE)", artist: "RM", cover: "mono.jpg" },
  { id: 76, title: "Bicycle", artist: "RM", cover: "Bicycle.jpg" },
  { id: 77, title: "Nuts", artist: "RM", cover: "RPWP.jpg" },
  { id: 78, title: "Moonchild", artist: "RM", cover: "mono.jpg" },
  { id: 79, title: "Around the world in a day(feat.Moses Sumney)", artist: "RM", cover: "RPWP.jpg" },
  { id: 80, title: "Come back to me", artist: "RM", cover: "RPWP.jpg" },


  { id: 81, title: "Nothing Without Your Love", artist: "Jin", cover: "Echo.jpg" },
  { id: 82, title: "Background", artist: "Jin", cover: "Echo.jpg" },
  { id: 83, title: "I will come to you", artist: "Jin", cover: "Happy.jpg" },
  { id: 84, title: "The Astronaut", artist: "Jin", cover: "TheAstronaut.jpg" },
  { id: 85, title: "Super Tuna", artist: "Jin", cover: "SuperTuna.jpg" },
  { id: 86, title: "Yours", artist: "Jin", cover: "Yours.jpg" },
  { id: 87, title: "Epiphany", artist: "Jin", cover: "LoveYourselfAnswer.jpg" },
  { id: 88, title: "Moon", artist: "Jin", cover: "MapofTheSoul7.jpg" },


  { id: 89, title: "Haegeum", artist: "SUGA", cover: "D-Day.jpg" },
  { id: 90, title: "AMYGDALA", artist: "SUGA", cover: "D-Day.jpg" },
  { id: 91, title: "SDL", artist: "SUGA", cover: "D-Day.jpg" },
  { id: 92, title: "Life Goes On by Suga", artist: "SUGA", cover: "D-Day.jpg" },
  { id: 93, title: "Daechwita", artist: "SUGA", cover: "D-2.jpg" },
  { id: 94, title: "People Pt.2 (feat. IU)", artist: "SUGA", cover: "PeoplePt2.jpg" },
  { id: 95, title: "Agust D", artist: "SUGA", cover: "Agust-D.jpg" },
  { id: 96, title: "Trivia : Seesaw", artist: "SUGA", cover: "LoveYourselfAnswer.jpg" },
  

  { id: 97, title: "i wonder (with Jung Kook)", artist: "j-hope", cover: "HopeOnTheStreet.jpg" },
  { id: 98, title: "Daydream", artist: "j-hope", cover: "HopeWorld.jpg" },
  { id: 99, title: "Outro : Ego", artist: "j-hope", cover: "MapofTheSoul7.jpg" },
  { id: 100, title: "Chicken Noodle Soup (feat. Becky G)", artist: "j-hope", cover: "CNS.jpg" },
  { id: 101, title: "Safety Zone", artist: "j-hope", cover: "JackInTheBox.jpg" },
  { id: 102, title: "on the street(solo version)", artist: "j-hope", cover: "HopeOnTheStreet.jpg" },
  { id: 103, title: "Killin' It Girl(feat. GloRilla)", artist: "j-hope", cover: "KIG.jpg" },
  { id: 104, title: "Arson", artist: "j-hope", cover: "JackInTheBox.jpg" },


  { id: 105, title: "Rebirth(Intro)", artist: "Jimin", cover: "Muse.jpg" },
  { id: 106, title: "Closer Than This", artist: "Jimin", cover: "CTT.jpg" },
  { id: 107, title: "Like Crazy", artist: "Jimin", cover: "Face.jpg" },
  { id: 108, title: "Promise", artist: "Jimin", cover: "promise.jpg" },
  { id: 109, title: "Serendipity(Full Length Edition)", artist: "Jimin", cover: "LoveYourselfAnswer.jpg" },
  { id: 110, title: "Lie", artist: "Jimin", cover: "Wings.jpg" },
  { id: 111, title: "With You", artist: "Jimin", cover: "withYou.jpg" },
  { id: 112, title: "편지(Dear. ARMY) - Letter", artist: "Jimin", cover: "Pyeonji.jpg" },




  { id: 113, title: "Winter Bear", artist: "V", cover: "WinterBear.jpg" },
  { id: 114, title: "Christmas Tree", artist: "V", cover: "ChristmasTree.jpg" },
  { id: 115, title: "Scenery", artist: "V", cover: "Scenery.jpg" },
  { id: 116, title: "For Us", artist: "V", cover: "Layover.jpg" },
  { id: 117, title: "FRI(END)S", artist: "V", cover: "Friends.jpg" },
  { id: 118, title: "Snow Flower (feat. Peakboy)", artist: "V", cover: "SnowFlower.jpg" },
  { id: 119, title: "Slow Dancing", artist: "V", cover: "Layover.jpg" },
  { id: 120, title: "Sweet Night", artist: "V", cover: "SweetNight.jpg" },


  { id: 121, title: "Hate You", artist: "Jungkook", cover: "Golden.jpg" },
  { id: 122, title: "Euphoria", artist: "Jungkook", cover: "LoveYourselfAnswer.jpg" },
  { id: 123, title: "Still with You", artist: "Jungkook", cover: "StillwithYou.jpg" },
  { id: 124, title: "My You", artist: "Jungkook", cover: "MyYou.jpg" },
  { id: 125, title: "Yes or No", artist: "Jungkook", cover: "Golden.jpg" },
  { id: 126, title: "3D (feat. Jack Harlow)", artist: "Jungkook", cover: "Golden.jpg" },
  { id: 127, title: "Seven (feat. Latto)", artist: "Jungkook", cover: "Seven.jpg" },
  { id: 128, title: "Too Sad to Dance", artist: "Jungkook", cover: "Golden.jpg" }
];


